### ISSUE TITLE
Please consider a LICENSE

### ISSUE THREAD

**Issue by qrush** [drasticactions/miiversearchive#2]
Awesome work, and big Splatoon fan here. I'd love to dive in and consider forking this and using the code in a different fashion, but any code that's published online and doesn't have a licensed attached is by default copyrighted to its owner. More on this:

https://blog.codinghorror.com/pick-a-license-any-license/
https://choosealicense.com/
https://opensource.org/faq

I'd say in interest of opening this up and letting others figure out how to mirror the images, please pick a permissive license. My favorite is MIT. It's just simple. 🐙 💚

**Comment by drasticactions** [comment]
Okay, I added MIT. I also updated the readme to be more upfront that this repo is more of a scratch one for figuring out best techniques for parsing and storing the data, so I can share that knowledge back to Archive Team, who are doing their own project using their tools.

So, IMO, the best way to contribute is to go to their IRC channel at [MiiWorse](http://chat.efnet.org:9090/?channels=%23miiworse), where I'm hanging out.
